#!/usr/bin/perl
=pod

SBX chooser

=head1 NAME

  sbx - Tool voor menu-selectie sandboxes.

=head1 DESCRIPTION

Keuze sandbox en het starten van de shell omgeving.

=head1 .sbxconfig

Configuratie file for your shell environment.

vb
   [foo]
      SBX=$HOME/sbx

=over 12

=item C<[item]>

Menu item shortname

=item C<SBX>

    Root of your sandbox
    The 'sb' alias return you to your sandbox.


=back

=head1 LICENSE

=head1 AUTHOR

Hans Mulder - H_Mulder@belastingdienst.nl

=head1 SEE ALSO

=cut

#
# GLOBALS in GLB

my %GLB={
            hostname => 'localhost'
        };
$GLB{hostname}=`hostname`;
$GLB{uname}=`uname`;
chomp $GLB{uname};
chomp $GLB{hostname};
#
#Terminal stuff
#- Prompt
#- Colors
package TERM;
my %color=(
        test => "\e[49;44m",
        bluebackgr => "\e[49;44m",
        yellowbackgr => "\e[49;43m",
        green => "\e[49;32m",
        greenbackgr => "\e[49;42m",
        redbackgr => "\e[49;41m",
        white => "\e[49;37m",
        lblue => "\e[49;36m",
        purple => "\e[49;35m",
        blue => "\e[49;34m",
        yellow => "\e[49;33m",
        red => "\e[49;31m"
        );
sub color_normal()
{
        return '^[[0m';
}
sub prompt()
{
    #export PS1="$(printf "${TITLE}$HOSTNAME:\$PWD>")"
    my $hostname=`hostname`;
    chomp $hostname;
    $ENV{PS1}  ="\\[\033]2;\${USER}@\${HOSTNAME} SBX \${SBX}\007\\]";#TITLE
    $ENV{PS1} .='\\['.$color{yellow}.'\\]'.$hostname.':${PWD} SB'.'\['.$color{white}.'\]'.'>';#path
}

#
#Registry stuff
#
package Win;
use Data::Dumper;
#use Win32::Registry;
my $reg='/cygdrive/c/Windows/System32/reg.exe';
#REG QUERY "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /s 
sub Query($)
{
  my $key=shift;
  my $q=$reg.' QUERY "'.$key.'" /s';
  my %keys;
  open(my $fh, '-|', $q) or die $!;
  while (my $l=<$fh>) {
    chomp $l;
    next if not $l =~ m/REG_/;
    #print "DBG:$l\n";
    my ($reg,$type,$val)=split(' ',$l,3);
    #print "DBG:reg $reg,$type,$val\n";
    $val =~ s/\r$//;
    $keys{$reg}= $val;
    #print 'DBG::$keys{'.$reg.'}="'.$val."\"\n";
  }
  close $fh;
	print "DBG:env==>".Dumper(\%keys)."\n";
  return %keys;
}
#
#CONFIG
#
package CONFIG;
use Data::Dumper;

my %CFG=();
sub  trim { my $s = shift; $s =~ s/^\s+|\s+$//g; return $s };
sub import()
{
  my $config_file="$ENV{HOME}/.sbxconfig";
  my $label="global";#default environment
  open CONFIG, $config_file or die "Could not open '$config_file':$!";
  while( <CONFIG> ){
    chomp;
    next if /^#/;#skip comment starting with #
    #$label = s/(^\[)||(\]$)// if /^\[/ ;
    s/[^\\]#.*//;  #strip comment
    if( m/^\[/ ){
      s/(^\[)||(\]$)//g;
      $label=$_;
    };
    if( m/=/ ){
      my ($var,$val)=split(/=/);
      $CFG{$label}{trim $var}= trim $val;
    }
  }
  #
	print "user_config".Dumper(\%CFG)."\n";
    
  close CONFIG;
}

#
# inject deps into given group
#
sub inject($)
{
  my $grp=shift;
  #print "grp is $grp ";
  #print "NODEPS $CFG{$grp}{'cfg.deps'}\n" if not $CFG{$grp}{'cfg.deps'};
  return 0 if not $CFG{$grp}{'cfg.deps'};
  my @deps=split /,/, $CFG{$grp}{'cfg.deps'};
  #print "DBG:deps are @deps\n";
  foreach my $ext_grp( @deps ){
    #print "deps = $_\n";
      foreach( keys $CFG{$ext_grp} ){
        #print "keys = $_\n";
        $CFG{$grp}{$_}=$CFG{$ext_grp}{$_};
      }
  }
}

sub get_group($)
{
  my $group=shift;
  return $CFG{$group};
}

#
#MENU
#
package MENU;
sub get_items()
{
  #TODO filter op menu
  my @items=();
  foreach my $grp ( keys %CFG ){
    push @items, $grp if $CFG{$grp}{'cfg.menu'} eq 'true';
  }
  return @items;
}
sub menu()
{
  my @options=get_items();

 	#!TODO enter toets geeft keuze en gaat dus door.
	my $nr=1;
	#print "user_menu".Dumper(\%menu)."\n";
	foreach(@options){
		print $nr++.") $_ ";
		print ":$CFG{$_}{'cfg.info'}";
		print "\n";
	}

	my $choice;
	while(1){
        	print "Select one [1..".($nr-1).']?';
        	$choice=<STDIN>;
		chomp $choice;
		$choice=1 if $choice eq '';#default
		last if $choice > 0 and $choice < $nr ;
	};

	return $options[$choice-1];
}

#
#Environment
#
package ENV;
use Data::Dumper;
sub export_grp($)
{
  my $group=shift;
  my $env=CONFIG::get_group($group);
  #print "DBG:env".Dumper($env)."\n";
  #TODO mbv export
  foreach( keys $env ) {
    $ENV{$_}=$env->{$_};
    #print "DBG:export $_, $ENV{$_} to $env->{$_}\n";
  }
}

#
# export hash to environemnt
#
sub export($)
{
  #print "DBG:env".Dumper(\@_)."\n";
  my $env=shift;
  #print "DBG:env".Dumper($env)."\n";
  foreach( keys $env ) {
    $ENV{$_}=$env->{$_};
    #print "DBG:export $_= $ENV{$_}\n";
  }

}
sub sub_vars($)
{
  my $group=shift;
  my $env=CONFIG::get_group($group);

  my $found=0;
  do{
    $found=0;
    foreach my $var ( keys $env ) {
      #$ENV{$_}=$env->{$_};
      #print "DBG:test $var\n";
      if( $env->{$var} =~ m/\$\{([^}]*)\}/ ){
          my $varvar=$1;
          $env->{$var} =~ s/\$\{[^}]*\}/$ENV{$varvar}/ if  $ENV{$varvar};
          #print "DBG:found $varvar, $ENV{$varvar} in \${} in $env->{$var}\n";
          $found=1;
        }
    }
  }while($found);
}
#
# Start shell
# Depends on cfg.type
# sh  : start sh
# cmd : start dos cmd.exe
sub start($)
{
  my $group=shift;
  my $env=CONFIG::get_group($group);
  #TODO start shell
  warn "Can not find dir '$ENV{SBXROOT}'\n" if not -d $ENV{SBXROOT};
  #print "DBG:chdir to '$ENV{SBXROOT}'\n";
  chdir( "$ENV{SBXROOT}" ) or die "$!";
  for( $env->{'cfg.type'} ){
    shell_sh()  if /^sh$/ ;
    shell_dos()  if /^dos$/ ;
    system( '/cygdrive/c/Windows/System32/cmd.exe')  if /^cdos$/ ;
    break;
  }
  #print "DBG:chdir( $ENV{SBXROOT} )\n";
  #system('sh');
}

sub shell_sh()
{
  #set ENV if noet set and files exists
  if( not $ENV{ENV} and -f "$ENV{SBXROOT}/.sbx_env" ){
	  $ENV{ENV}=$ENV{SBXROOT}.'/.sbx_env';
  }
  TERM::prompt();
  system('sh');
}
sub shell_dos()
{
    my %env=Win::Query( 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment');
    my $PATH=$env{Path};
    ENV::export(\%env);
    %env=Win::Query( 'HKCU\Environment');
    $env{Path}=$PATH.';'.$env{Path};
    ENV::export(\%env);
    system('/cygdrive/c/Windows/System32/cmd.exe');
}
#
# SBX utilities
#
package SBX;
sub info()
{
	print "Sandbox info:\n";
	print "Doesn't look like a sandbox, environment not set SBX='$ENV{SBX}'\n" if not $ENV{SBX};
	if( -e "$ENV{ENV}" ){
		print "Environemnt INFO uit '$ENV{ENV}'\n";
		my @info=grep(!/#INFO_/,`sed -n '/INFO_START/,/INFO_STOP/p' '$ENV{ENV}'`);
		print @info;
	}
}
#
# MAIN
# 
package MAIN;
use Data::Dumper;

my $test=0;
if($test){
  my %env=Win::Query( 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment');
	print "DBG:env==>".Dumper(\%env)."\n";
  print "DBG:stop\n";
  exit 100;
}

if( $ARGV[0] eq 'info' ){
	SBX::info();
	exit 0;
}
print "Start\n";
CONFIG::import();
my $choice=MENU::menu();
print "choice=$choice\n";
CONFIG::inject($choice);
ENV::export_grp($choice);
ENV::sub_vars($choice);
ENV::export_grp($choice);
ENV::start($choice);
